grumphp:
  hooks_dir: ~
  hooks_preset: local
  stop_on_failure: false
  ignore_unstaged_changes: false
  hide_circumvention_tip: false
  process_timeout: 120
  fixer:
    enabled: true
    fix_by_default: false
  tasks:
    phpcs:
      standard: vendor/voyager/php-quality-tools/configs/phpcs.xml
      triggered_by: ['php']
      ignore_patterns:
        - vendor/
        - node_modules/
        - storage/
        - cache/
    phpstan:
      configuration: vendor/voyager/php-quality-tools/configs/phpstan.neon
      level: 5
      triggered_by: ['php']
      ignore_patterns:
        - vendor/
        - node_modules/
        - storage/
        - cache/
    phplint:
      exclude: ['vendor', 'node_modules', 'storage', 'cache']
      jobs: ~
      short_open_tag: false
      triggered_by: ['php']
